f = open("c:\\temp\\t3.txt", "w")
f.write("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris consequat luctus pellentesque.\n")
f.write("Vivamus sed sapien lectus.\n\n")
f.write("한글")
f.close()